# Generated by Django 5.2.7 on 2025-10-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
